services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - RPP_DISCORD_CLIENT_ID=111....1111
            - RPP_DISCORD_TOKEN=token
        container_name: rpp
        volumes:
            - ./credentials:/home/node/app/credentials
            - ./instances:/home/node/app/instances
            - ./logs:/home/node/app/logs
            - ./maps:/home/node/app/maps
